service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-northeast-1
    # Environment variables
    environment: ${file(./environment.yml)}

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:

    # This function runs the Laravel website/API
    # web:
    #     handler: public/index.php
    #     runtime: php-83-fpm
    #     timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    #     events:
    #         - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-83-console
        timeout: 720 # in seconds
        events:
            - schedule:
                rate: cron(0 0 ? * MON-FRI *)
                input: '"app:article-summary-notice"'


plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
